[package]
name = "WhiteOS"
version = "0.1.0"
edition = "2024"

[dependencies]
limine = "0.6.3"
spin = "0.10.0"
log = { version = "0.4.29", features = [
    "max_level_debug",
    "release_max_level_warn",
] }
polished_serial_logging = "0.1.2"
x86_64 = "0.15.4"
lazy_static = { version = "1.5.0", default-features = false, features = [
    "spin_no_std",
] }
pic8259 = "0.11.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[lib]
name = "WhiteOS"
test = false
bench = false

[[bin]]
name = "WhiteOS"
test = false
bench = false
